### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by MadsBock** [MercantecData/serverside-programmering-littleyoru#2]
Jeg vil gerne have du laver en pull request hvori du specificerer i punktform hvilke af opgaverne på learnspace der er at finde i din portfolio på nuværende tidspunkt i færdig form. 

Fremadrettet vil jeg gerne bede dig lave en pull request når du er færdig med en ny opgave.

**Comment by littleyoru** [comment]
Har lavet en pull request
